### ISSUE TITLE
Deploy workflow stable branch compatibility

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/zeebe-process-test#231]
## Description

We will have to support stable branches starting from the `1.4.0` release. Currently this will not work properly. This is because in our pipeline we have the "Build and deploy to Maven" step:
```yaml
- name: Build and deploy to Maven
  id: release
  uses: camunda-community-hub/community-action-maven-release@v1.0.12
  with:
    release-version: ${{ github.event.release.tag_name }}
    release-profile: community-action-maven-release
    nexus-usr: ${{ steps.secrets.outputs.ARTIFACTS_USR }}
    nexus-psw: ${{ steps.secrets.outputs.ARTIFACTS_PSW }}
    maven-usr: ${{ steps.secrets.outputs.MAVEN_CENTRAL_DEPLOYMENT_USR }}
    maven-psw: ${{ steps.secrets.outputs.MAVEN_CENTRAL_DEPLOYMENT_PSW }}
    maven-gpg-passphrase: ${{ steps.secrets.outputs.MAVEN_CENTRAL_GPG_SIGNING_KEY_PASSPHRASE }}
    maven-url: s01.oss.sonatype.org
    github-token: ${{ secrets.GITHUB_TOKEN }}
```

One of the things this action does is updating the project version in the pom files. By default it does this change on the default branch, which in our case is `main`.  At the moment I don't see a way to change this to a different branch. This means we have 2 options.

1. We stop using this action and add our own steps for deploying to Maven.
2. We make a change in the [community-action-maven-release](https://github.com/camunda-community-hub/community-action-maven-release) to support different branches. In our workflow we'd have to figure out which stable branch we need to use.
